ALTER TABLE GAT.GAT_OBJETOS_GENERADOS ADD (
  CONSTRAINT OBGE_TOBJ_FK2 
  FOREIGN KEY (TOBJ_CODIGO) 
  REFERENCES GAT.GAT_TIP_OBJETOS (TOBJ_CODIGO)
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GAT_OBJETOS_GENERADOS ADD (
  CONSTRAINT OBGE_PROD_FK1 
  FOREIGN KEY (PROD_ID) 
  REFERENCES GAT.GAT_PRODUCTOS (PROD_ID)
  ENABLE VALIDATE)
/

