ALTER TABLE GAT.GAT_REL_TPLT_TPAC ADD (
  CONSTRAINT TPTP_TPLT_FK2 
  FOREIGN KEY (PERF_ID, TTEM_CODIGO) 
  REFERENCES GAT.GAT_TEMPLATES (PERF_ID,TTEM_CODIGO)
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GAT_REL_TPLT_TPAC ADD (
  CONSTRAINT TPTP_TPAC_FK1 
  FOREIGN KEY (TPAC_CODIGO) 
  REFERENCES GAT.GAT_TIP_PACKAGES (TPAC_CODIGO)
  ENABLE VALIDATE)
/

