ALTER TABLE GAT.GAT_TEMPLATES ADD (
  CONSTRAINT TPLT_TTEM_FK2 
  FOREIGN KEY (TTEM_CODIGO) 
  REFERENCES GAT.GAT_TIP_TEMPLATES (TTEM_CODIGO)
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GAT_TEMPLATES ADD (
  CONSTRAINT TPLT_PERF_FK1 
  FOREIGN KEY (PERF_ID) 
  REFERENCES GAT.GAT_PERFILES (PERF_ID)
  ENABLE VALIDATE)
/

