ALTER TABLE GAT.GAT_PRODUCTOS ADD (
  CONSTRAINT PROD_PERF_FK3 
  FOREIGN KEY (PERF_ID) 
  REFERENCES GAT.GAT_PERFILES (PERF_ID)
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GAT_PRODUCTOS ADD (
  CONSTRAINT PROD_CLIE_FK2 
  FOREIGN KEY (CLIE_ID) 
  REFERENCES GAT.CLI_CLIENTES (CLIE_ID)
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GAT_PRODUCTOS ADD (
  CONSTRAINT PROD_APPL_FK1 
  FOREIGN KEY (APPL_ID) 
  REFERENCES GAT.APP_APLICACIONES (APPL_ID)
  ENABLE VALIDATE)
/

