ALTER TABLE GAT.GAT_OBJETOS_GENERADOS ADD (
  CONSTRAINT OBGE_COMPILADO_CCC
  CHECK ( COMPILADO IN ('N', 'S'))
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GAT_OBJETOS_GENERADOS ADD (
  CONSTRAINT OBGE_PK
  PRIMARY KEY
  (PROD_ID, NOMBRE_OBJETO, TOBJ_CODIGO)
  USING INDEX GAT.OBGE_PK
  ENABLE VALIDATE)
/

