ALTER TABLE GAT.GJC_TO_CATALOG_OLD ADD (
  CONSTRAINT TOCA_PK
  PRIMARY KEY
  (PERF_ID, TOCA_CODIGO)
  USING INDEX GAT.TOCA_PK
  ENABLE VALIDATE)
/

ALTER TABLE GAT.GJC_TO_CATALOG_OLD ADD (
  CONSTRAINT TOCA_UK1
  UNIQUE (PERF_ID, SERIAL_VERSION_UID)
  USING INDEX GAT.TOCA_UK1
  ENABLE VALIDATE)
/

