CREATE TABLE GAT.BAP_CATALOGO
(
  OWNER           VARCHAR2(30 BYTE),
  TABLE_NAME      VARCHAR2(30 BYTE),
  TABLE_PREFIX    VARCHAR2(3 BYTE),
  TABLE_SUBJECT   VARCHAR2(26 BYTE),
  NOMBRE_PACKAGE  VARCHAR2(4000 BYTE),
  TPAC_CODIGO     VARCHAR2(2 BYTE),
  OBJECT_TYPE     CHAR(7 BYTE),
  EXISTE          CHAR(1 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
/


