CREATE TABLE GAT.GAT_TIP_PARAMETROS
(
  TIPR_CODIGO         VARCHAR2(6 BYTE)          NOT NULL,
  NOMBRE              VARCHAR2(30 BYTE)         NOT NULL,
  AUD_CREADO_EN       TIMESTAMP(6)              DEFAULT LOCALTIMESTAMP        NOT NULL,
  AUD_CREADO_POR      VARCHAR2(45 BYTE)         DEFAULT USER                  NOT NULL,
  AUD_MODIFICADO_EN   TIMESTAMP(6),
  AUD_MODIFICADO_POR  VARCHAR2(45 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
/


