CREATE TABLE GAT.GAT_PERFILES
(
  PERF_ID             NUMBER(10)                NOT NULL,
  EMPRESA             VARCHAR2(60 BYTE)         NOT NULL,
  NOMBRE              VARCHAR2(120 BYTE)        NOT NULL,
  NOMBRE_CORTO        VARCHAR2(6 BYTE)          NOT NULL,
  DESCRIPCION         VARCHAR2(800 BYTE),
  AUD_CREADO_EN       TIMESTAMP(6)              DEFAULT LOCALTIMESTAMP        NOT NULL,
  AUD_CREADO_POR      VARCHAR2(45 BYTE)         DEFAULT USER                  NOT NULL,
  AUD_MODIFICADO_EN   TIMESTAMP(6),
  AUD_MODIFICADO_POR  VARCHAR2(45 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
/


