CREATE TABLE GAT.GAT_OBJETOS_GENERADOS
(
  PROD_ID             NUMBER(10)                NOT NULL,
  NOMBRE_OBJETO       VARCHAR2(30 BYTE)         NOT NULL,
  TOBJ_CODIGO         VARCHAR2(30 BYTE)         NOT NULL,
  PRIMERA_GENERACION  TIMESTAMP(6)              NOT NULL,
  ULTIMA_GENERACION   TIMESTAMP(6)              NOT NULL,
  VERSION_GENERADOR   VARCHAR2(25 BYTE),
  TOTAL_GENERACIONES  NUMBER(6)                 NOT NULL,
  COMPILADO           VARCHAR2(1 BYTE),
  AUD_CREADO_EN       TIMESTAMP(6)              DEFAULT LOCALTIMESTAMP        NOT NULL,
  AUD_CREADO_POR      VARCHAR2(45 BYTE)         DEFAULT USER                  NOT NULL,
  AUD_MODIFICADO_EN   TIMESTAMP(6),
  AUD_MODIFICADO_POR  VARCHAR2(45 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
/

COMMENT ON COLUMN GAT.GAT_OBJETOS_GENERADOS.TOBJ_CODIGO IS 'Tipo de objeto'
/

COMMENT ON COLUMN GAT.GAT_OBJETOS_GENERADOS.PRIMERA_GENERACION IS 'Primera vez que fue generado'
/

COMMENT ON COLUMN GAT.GAT_OBJETOS_GENERADOS.ULTIMA_GENERACION IS 'Última vez que el Generador de Java generó el código'
/

COMMENT ON COLUMN GAT.GAT_OBJETOS_GENERADOS.VERSION_GENERADOR IS 'Versión del generador con la cual fue hecha la última generación'
/



