CREATE TABLE GAT.GAT_REL_TPLT_TPAC
(
  PERF_ID             NUMBER(10)                NOT NULL,
  TTEM_CODIGO         VARCHAR2(15 BYTE)         NOT NULL,
  TPAC_CODIGO         VARCHAR2(2 BYTE)          NOT NULL,
  DESCRIPCION         VARCHAR2(240 BYTE),
  AUD_CREADO_EN       TIMESTAMP(6)              DEFAULT LOCALTIMESTAMP        NOT NULL,
  AUD_CREADO_POR      VARCHAR2(45 BYTE)         DEFAULT USER                  NOT NULL,
  AUD_MODIFICADO_EN   TIMESTAMP(6),
  AUD_MODIFICADO_POR  VARCHAR2(45 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
/

COMMENT ON TABLE GAT.GAT_REL_TPLT_TPAC IS 'Relación entre los Templates y Tipos de packages'
/

COMMENT ON COLUMN GAT.GAT_REL_TPLT_TPAC.DESCRIPCION IS 'Descripción que se utiliza en el Encabezado del Package'
/



