CREATE TABLE GAT.GAT_TEMPLATE_MAP
(
  PERF_ID             NUMBER(10)                NOT NULL,
  TTEM_CODIGO         VARCHAR2(15 BYTE)         NOT NULL,
  PARA_CODE           VARCHAR2(60 BYTE)         NOT NULL,
  TIPR_CODIGO         VARCHAR2(6 BYTE)          NOT NULL,
  COMPONENT           VARCHAR2(2000 BYTE),
  SUBCOMPONENT        VARCHAR2(30 BYTE),
  AUD_CREADO_EN       TIMESTAMP(6)              DEFAULT LOCALTIMESTAMP        NOT NULL,
  AUD_CREADO_POR      VARCHAR2(45 BYTE)         DEFAULT USER                  NOT NULL,
  AUD_MODIFICADO_EN   TIMESTAMP(6),
  AUD_MODIFICADO_POR  VARCHAR2(45 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
/

COMMENT ON TABLE GAT.GAT_TEMPLATE_MAP IS 'Mapa de template'
/



